"""create systems and organs tables

Revision ID: 5c5b016c9816
Revises: 
Create Date: 2026-08-17 18:28:09.221471

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5c5b016c9816'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('systems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_systems_slug'), ['slug'], unique=True)

    op.create_table('organs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('mesh_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organs_mesh_id'), ['mesh_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_organs_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organs_slug'))
        batch_op.drop_index(batch_op.f('ix_organs_mesh_id'))

    op.drop_table('organs')
    with op.batch_alter_table('systems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_systems_slug'))

    op.drop_table('systems')
    # ### end Alembic commands ###
